### ISSUE TITLE
Make str.replace strict?

### ISSUE THREAD

**Issue by fritx** [sindresorhus/tildify#3]
Hey @sindresorhus 
How about this? also would work in `untildify`

```js
module.exports = function (str) {
	return str.replace(home, '~');
};
```
=>
```js
module.exports = function (str) {
  str += path.sep;
  str = str.replace(home + path.sep, '~' + path.sep);
  str = str.slice(0, -1);
  return str;
};
```

```js
test(function (t) {
  var fixture = home;
  t.assert(tildify(fixture) === '~');
  t.end();
});

test(function (t) {
  var fixture = path.resolve(home, 'tildify');
  t.assert(tildify(fixture)[0] === '~');
  t.assert(/tildify$/.test(tildify(fixture)));
  t.assert(tildify(fixture) !== fixture);
  t.end();
});

test(function (t) {
  var fixture = path.resolve(home + 'foo', 'tildify');
  t.assert(tildify(fixture) === fixture);
  t.end();
});
```

![image](https://cloud.githubusercontent.com/assets/6647633/9806974/d3669c8e-587e-11e5-8e1d-8cd6fbfcec9c.png)

**Comment by sindresorhus** [comment]
I'm not exactly sure what you're asking here? Can you succinctly explain it?

**Comment by fritx** [comment]
Ok. We should make sure that `tildify` applied to `path.resolve(home, 'tildify')` and not to `path.resolve(home + 'foo', 'tildify')` (which is not a homedir)

**Comment by sindresorhus** [comment]
Oh yeah. I doubt that will ever happen, but I agree, doesn't hurt to be strict. Wanna do a PR?

**Comment by fritx** [comment]
Thanks. I'm ready for this PR.
